version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Your_Password123
      - ACCEPT_EULA=Y
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: