from .personal import Personal
from .base_csv_model import BaseCSVModel
from .vacacion import Vacacion
from .falta import Falta
from .persona_natural import PersonaNatural
from .autorizar_h_e import AutorizarHE
from .concepto_aplicado import ConceptoAplicado
from .dato_extra import DatoExtra
from .licencia import Licencia
